// ============================================
// PHANTOM FINANCE - DEMO DATA (Mom's Budget)
// ============================================

export const demoData = {
  version: 1,
  profile: {
    name: "Budget Template",
    currency: "USD"
  },
  income: [
    { id: "inc1", name: "Primary Income", amount: 9500, frequency: "monthly" }
  ],
  monthlyExpenses: [
    { id: "exp1", name: "Cameras Monthly", amount: 20, category: "Subscriptions", dueDay: 16, autoPay: true },
    { id: "exp2", name: "Food / Groceries", amount: 1200, category: "Food", dueDay: 1, autoPay: false },
    { id: "exp3", name: "Cleaning Supplies", amount: 150, category: "Personal", dueDay: 1, autoPay: false },
    { id: "exp4", name: "Electricity", amount: 325, category: "Utilities", dueDay: 6, autoPay: true },
    { id: "exp5", name: "Health Insurance", amount: 0, category: "Insurance", dueDay: 15, autoPay: true },
    { id: "exp6", name: "Cell Phone", amount: 225, category: "Phone", dueDay: 6, autoPay: true },
    { id: "exp7", name: "Gas / Fuel", amount: 300, category: "Transportation", dueDay: 1, autoPay: false },
    { id: "exp8", name: "Internet", amount: 85, category: "Internet", dueDay: 8, autoPay: true },
    { id: "exp9", name: "Netflix / Streaming", amount: 55, category: "Entertainment", dueDay: 9, autoPay: true },
    { id: "exp10", name: "Water", amount: 80, category: "Utilities", dueDay: 1, autoPay: true }
  ],
  debts: [
    { id: "d1", name: "Lowes", monthlyPayment: 11, totalDebt: 201.96, originalDebt: 201.96, dueDay: 15, interestRate: "0%", notes: "", category: "credit-card" },
    { id: "d2", name: "Care Credit", monthlyPayment: 12, totalDebt: 199.55, originalDebt: 199.55, dueDay: 17, interestRate: "0%", notes: "", category: "medical" },
    { id: "d3", name: "Home Design (Pool Table)", monthlyPayment: 48, totalDebt: 863.69, originalDebt: 863.69, dueDay: 16, interestRate: "0%", notes: "", category: "credit-card" },
    { id: "d4", name: "Ashley Furniture", monthlyPayment: 39, totalDebt: 790.90, originalDebt: 790.90, dueDay: 11, interestRate: "0%", notes: "", category: "credit-card" },
    { id: "d5", name: "Crate and Barrel", monthlyPayment: 33, totalDebt: 802.97, originalDebt: 802.97, dueDay: 20, interestRate: "0%", notes: "", category: "credit-card" },
    { id: "d6", name: "Home Depot #7158", monthlyPayment: 76, totalDebt: 1516.36, originalDebt: 1516.36, dueDay: 16, interestRate: "0%", notes: "", category: "credit-card" },
    { id: "d7", name: "Home Depot 3", monthlyPayment: 18, totalDebt: 303.03, originalDebt: 303.03, dueDay: 22, interestRate: "0%", notes: "", category: "credit-card" },
    { id: "d8", name: "Amazon (Affirm)", monthlyPayment: 90.34, totalDebt: 722.69, originalDebt: 722.69, dueDay: 17, interestRate: "Affirm", notes: "", category: "credit-card" },
    { id: "d9", name: "Amazon Computer (Affirm)", monthlyPayment: 56.97, totalDebt: 1302.68, originalDebt: 1302.68, dueDay: 23, interestRate: "Affirm", notes: "Try to pay off early", category: "credit-card" },
    { id: "d10", name: "Hecland Cookware (Affirm)", monthlyPayment: 157.50, totalDebt: 1102.49, originalDebt: 1102.49, dueDay: 8, interestRate: "Affirm", notes: "", category: "general" },
    { id: "d11", name: "Jared (Affirm)", monthlyPayment: 116.63, totalDebt: 1049.59, originalDebt: 1049.59, dueDay: 2, interestRate: "Affirm", notes: "", category: "general" },
    { id: "d12", name: "Auto Loan", monthlyPayment: 461.69, totalDebt: 7094.32, originalDebt: 7094.32, dueDay: 28, interestRate: "", notes: "", category: "auto" },
    { id: "d13", name: "SBA Loan", monthlyPayment: 1350, totalDebt: 282000, originalDebt: 282000, dueDay: 16, interestRate: "", notes: "", category: "business" },
    { id: "d14", name: "Cherry Payment 1", monthlyPayment: 87.66, totalDebt: 1073.38, originalDebt: 1073.38, dueDay: 2, interestRate: "", notes: "Ends April 2027", category: "medical" },
    { id: "d15", name: "Cherry Payment 2", monthlyPayment: 94.67, totalDebt: 1108.04, originalDebt: 1108.04, dueDay: 25, interestRate: "", notes: "Ends April 2027", category: "medical" },
    { id: "d16", name: "Mortgage", monthlyPayment: 1573.41, totalDebt: 140963.74, originalDebt: 140963.74, dueDay: 1, interestRate: "", notes: "", category: "mortgage" },
    { id: "d17", name: "Ygrene (Windows)", monthlyPayment: 0, totalDebt: 20164.30, originalDebt: 20164.30, dueDay: 0, interestRate: "", notes: "Added to property tax", category: "mortgage" },
    { id: "d18", name: "Student Loan", monthlyPayment: 85, totalDebt: 165000, originalDebt: 165000, dueDay: 15, interestRate: "", notes: "", category: "student" },
    { id: "d19", name: "Water Treatment Equipment", monthlyPayment: 112.89, totalDebt: 6285.75, originalDebt: 6285.75, dueDay: 15, interestRate: "", notes: "", category: "general" },
    { id: "d20", name: "Retirement Plan (National Life)", monthlyPayment: 380, totalDebt: 13000, originalDebt: 13000, dueDay: 25, interestRate: "", notes: "", category: "general" },
    { id: "d21", name: "Silvia Crate & Barrel", monthlyPayment: 50, totalDebt: 3595.98, originalDebt: 3595.98, dueDay: 0, interestRate: "", notes: "", category: "credit-card" },
    { id: "d22", name: "Banana Republic", monthlyPayment: 30, totalDebt: 969.64, originalDebt: 969.64, dueDay: 2, interestRate: "", notes: "", category: "credit-card" },
    { id: "d23", name: "Ann Taylor", monthlyPayment: 30, totalDebt: 431.48, originalDebt: 431.48, dueDay: 18, interestRate: "", notes: "", category: "credit-card" },
    { id: "d24", name: "PayPal", monthlyPayment: 129, totalDebt: 3792.95, originalDebt: 3792.95, dueDay: 8, interestRate: "", notes: "", category: "credit-card" },
    { id: "d25", name: "Goodyear", monthlyPayment: 40, totalDebt: 450, originalDebt: 450, dueDay: 16, interestRate: "", notes: "", category: "auto" },
    { id: "d26", name: "Capital One Empire #5589", monthlyPayment: 65, totalDebt: 1975.17, originalDebt: 1975.17, dueDay: 18, interestRate: "", notes: "Empire Group", category: "business" },
    { id: "d27", name: "Capital One Imperial #6987", monthlyPayment: 15, totalDebt: 460.82, originalDebt: 460.82, dueDay: 18, interestRate: "", notes: "Imperial Delivery", category: "business" },
    { id: "d28", name: "Capital One Master #6740", monthlyPayment: 65, totalDebt: 2097.66, originalDebt: 2097.66, dueDay: 18, interestRate: "", notes: "", category: "business" },
    { id: "d29", name: "Capital One Personal", monthlyPayment: 34, totalDebt: 500.66, originalDebt: 500.66, dueDay: 18, interestRate: "", notes: "", category: "credit-card" },
    { id: "d30", name: "Nordstrom", monthlyPayment: 55, totalDebt: 1517.36, originalDebt: 1517.36, dueDay: 2, interestRate: "", notes: "", category: "credit-card" },
    { id: "d31", name: "IRS Debt 2022", monthlyPayment: 225, totalDebt: 1527.14, originalDebt: 1527.14, dueDay: 15, interestRate: "", notes: "", category: "irs" },
    { id: "d32", name: "IRS Debt 2023", monthlyPayment: 0, totalDebt: 11225.53, originalDebt: 11225.53, dueDay: 0, interestRate: "", notes: "", category: "irs" },
    { id: "d33", name: "IRS Debt 2024", monthlyPayment: 0, totalDebt: 9875.96, originalDebt: 9875.96, dueDay: 0, interestRate: "", notes: "", category: "irs" },
    { id: "d34", name: "Chase (Business)", monthlyPayment: 202, totalDebt: 4705.41, originalDebt: 4705.41, dueDay: 13, interestRate: "", notes: "", category: "business" },
    { id: "d35", name: "BOA Personal", monthlyPayment: 170, totalDebt: 4429.25, originalDebt: 4429.25, dueDay: 3, interestRate: "", notes: "", category: "credit-card" },
    { id: "d36", name: "BOA Accuracy", monthlyPayment: 350, totalDebt: 11700, originalDebt: 11700, dueDay: 6, interestRate: "", notes: "", category: "business" }
  ],
  propertyExpenses: [
    { id: "p1", name: "Closets", cost: 6500, completed: true },
    { id: "p2", name: "Window Curtains", cost: 2500, completed: false },
    { id: "p3", name: "Finishing Work", cost: 3000, completed: true },
    { id: "p4", name: "Flooring Material", cost: 5500, completed: true },
    { id: "p5", name: "Flooring Installation", cost: 7000, completed: true },
    { id: "p6", name: "Interior Doors", cost: 4000, completed: false },
    { id: "p7", name: "Bathroom Glass Door", cost: 1750, completed: false },
    { id: "p8", name: "Hallway Bathroom", cost: 5500, completed: false },
    { id: "p9", name: "Kitchen Cabinets & Countertop", cost: 7000, completed: false },
    { id: "p10", name: "Concrete Work", cost: 6000, completed: true },
    { id: "p11", name: "Plumbing", cost: 3700, completed: true },
    { id: "p12", name: "Electrician", cost: 3100, completed: true },
    { id: "p13", name: "Materials", cost: 20000, completed: true },
    { id: "p14", name: "Fence", cost: 7000, completed: false },
    { id: "p15", name: "Windows", cost: 20000, completed: true },
    { id: "p16", name: "Bedroom Bathroom", cost: 4000, completed: false },
    { id: "p17", name: "Exterior & Garage Finish", cost: 3500, completed: false },
    { id: "p18", name: "Kitchen Patio Granite", cost: 4000, completed: false },
    { id: "p19", name: "Dumpster Rental", cost: 2400, completed: true },
    { id: "p20", name: "Garage Door", cost: 4500, completed: false },
    { id: "p21", name: "Pavers", cost: 22000, completed: false },
    { id: "p22", name: "Painting (Interior)", cost: 3500, completed: true },
    { id: "p23", name: "Additional Work", cost: 4500, completed: false },
    { id: "p24", name: "Garage Floor", cost: 1000, completed: false },
    { id: "p25", name: "Outdoor Kitchen Furniture", cost: 3700, completed: false },
    { id: "p26", name: "Refrigerator", cost: 3500, completed: false },
    { id: "p27", name: "Oven & Microwave", cost: 3700, completed: false },
    { id: "p28", name: "Kitchen Wine Cooler", cost: 700, completed: false },
    { id: "p29", name: "Outdoor Terrace Floor", cost: 3500, completed: false },
    { id: "p30", name: "Landscaping", cost: 1200, completed: false },
    { id: "p31", name: "Outdoor Terrace Materials", cost: 15000, completed: false },
    { id: "p32", name: "Guest Room", cost: 6000, completed: false }
  ],
  annualBudget: [
    { id: "a1", name: "Total Revenue", amount: 250000, isIncome: true },
    { id: "a2", name: "Mortgage", amount: 15235, isIncome: false },
    { id: "a3", name: "Business Operating", amount: 20000, isIncome: false },
    { id: "a4", name: "SBA Loan", amount: 16200, isIncome: false },
    { id: "a5", name: "Retirement Plan", amount: 14000, isIncome: false },
    { id: "a6", name: "Personal Debts", amount: 7400, isIncome: false },
    { id: "a7", name: "Bills & Food", amount: 70000, isIncome: false },
    { id: "a8", name: "IRS Debt", amount: 16000, isIncome: false }
  ],
  businessExpenses: [
    { id: "b1", name: "Social Media Management", monthlyCost: 0, annualCost: 0, category: "Marketing" },
    { id: "b2", name: "Insurance", monthlyCost: 83.33, annualCost: 1000, category: "Insurance" },
    { id: "b3", name: "QuickBooks", monthlyCost: 233.33, annualCost: 2800, category: "Accounting" },
    { id: "b4", name: "Ultra Tax", monthlyCost: 166.67, annualCost: 2000, category: "Software" },
    { id: "b5", name: "Cloud Storage", monthlyCost: 45, annualCost: 540, category: "Cloud" },
    { id: "b6", name: "DocuSign", monthlyCost: 83.33, annualCost: 1000, category: "Software" },
    { id: "b7", name: "MetroFax", monthlyCost: 14.58, annualCost: 175, category: "Communication" },
    { id: "b8", name: "Office Phone", monthlyCost: 25, annualCost: 300, category: "Communication" },
    { id: "b9", name: "Website Hosting", monthlyCost: 8.08, annualCost: 97, category: "Software" },
    { id: "b10", name: "Zoom", monthlyCost: 12.49, annualCost: 149.90, category: "Communication" },
    { id: "b11", name: "DocuClipper", monthlyCost: 83.33, annualCost: 1000, category: "Software" },
    { id: "b12", name: "Other Subscriptions", monthlyCost: 83.33, annualCost: 1000, category: "Subscriptions" }
  ],
  settings: {
    theme: "dark",
    language: "en"
  }
};
